instagram/urls.py
from django.contrib import admin
from django.urls import path, include
#apps
from instagram import views as local_views


# for static django files
from django.conf import settings
from django.conf.urls.static import static


media_path= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
static_path = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = [
    # local views
    path('admin/', admin.site.urls),
    path(r'', include('django.contrib.auth.urls')),
    path('test/', local_views.test, name='test'),



    # posts views
    path('', include('posts.urls', namespace='posts')),

    #user views
    path('users/', include('users.urls', namespace='users')),


] + media_path + static_path

posts/urls.py
"""Posts urls"""
from django.urls import path
from posts import views



app_name = 'posts'
urlpatterns = [
path('', views.PostsFeedView.as_view(), name='feed'),
path('post/<int:pk>/', views.PostDetailView.as_view(), name='detail' ),
path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='update' ),
path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete' ),
path('post/create/', views.CreatePostView.as_view(), name='create_post' ),
path('post/<int:pk>/comment/create/', views.PostCreateCommentView.as_view(), name='create_comment' ),
path('post/<int:post>/<str:instruction>/', views.like_or_dislike_post, name= 'likeordislikepost'),
]

posts/models.py
"""Posts models."""

#Django
from django.db import models
from django.contrib.auth.models import User
from users.models import Profile
from django import template
# Create your models here.


class Post(models.Model):
    """Post model class for post"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, blank=True, null=True)
    photo = models.ImageField(upload_to='posts/photo')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, blank=True, related_name='likes')

    
    def comments_count(self):
        return Comment.objects.filter(post=self.pk).count()

    def likes_count(self):
        return self.likes.count()

    def __str__(self):
        return f'{self.title} by @{self.user}'


class Comment(models.Model):
    """Comment model for posts"""
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    text = models.TextField(default="", max_length=300,)
    likes = models.ManyToManyField(User, blank=True, related_name='like')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    @classmethod
    def comments_count(cls, some_post):
        return cls.objects.filter(post=some_post.pk).count()

    def likes_count(self):
        return self.likes.count()

    def __str__(self):
        return f'by {self.user.username}: {self.text}'

posts/forms.py
"""Users Form"""
# django
from django.forms import ModelForm
from posts.models import Post, Comment
from django.forms.widgets import FileInput, Textarea

# forms


class PostForm(ModelForm):
    """Post form"""

    class Meta:
        model = Post
        fields = ['user', 'profile', 'title', 'photo', 'likes']
        exclude=['user', 'profile','likes']
        widgets = {'photo': FileInput(attrs={'class': 'form-control'}),

         }


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ['post', 'user', 'text', 'likes', 'profile']
        exclude= ['user', 'likes', 'profile', 'post']
        widgets={'text': Textarea(attrs={
            'class': 'form-control',
            'cols' : 1,
            'rows': 1,
            'placeholder': 'Insert your comment',
            'required': True,
            'labels': False,
        }),
        }

posts/views.py
"""POSTS VIEWS"""

#django
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from django.views.generic.edit import UpdateView, FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect, render
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.http import JsonResponse

#forms
from posts.forms import PostForm, CommentForm

#models
from posts.models import Post, Comment
# Create your views here.


@login_required
def like_or_dislike_post(request, post, instruction):
    """Like or dislike Posts"""
    current_user= request.user
    post = get_object_or_404(Post, pk=post)

    if instruction =='like':
        post.likes.add(current_user)
    else:
        post.likes.remove(current_user)

    count = post.likes.count()

    return JsonResponse({'likes': count})
    

class PostUpdateView(UpdateView, LoginRequiredMixin):
    """Single post view"""
    model = Post
    template_name = 'posts/update_post.html'
    form_class = PostForm

    def get_success_url(self):
        pk = self.object.pk
        return reverse('posts:detail', kwargs={'pk': pk})

class PostDeleteView(DeleteView, LoginRequiredMixin):
    """Delete post view"""
    model = Post


    def get_success_url(self):
        username = self.request.user.username
        return reverse('users:detail', kwargs={'username': username})

class PostDetailView(DetailView, LoginRequiredMixin):
    """Single post view"""
    model = Post
    context_object_name = 'post'
    template_name = 'posts/detail.html'



class PostsFeedView(LoginRequiredMixin, ListView):
    """Views that list all posts"""
    ordering = ('-created')
    context_object_name = 'posts'
    template_name = 'posts/feed.html'
    paginate_by = 100
    model = Post


class CreatePostView(LoginRequiredMixin, CreateView):
    """View for a new post creation"""
    model = Post
    form_class = PostForm
    template_name = 'posts/new.html'
    
    def form_valid(self, form):
        """creates a form instance
         for hidden user and profile fields"""
        form.instance.user = self.request.user
        form.instance.profile = self.request.user.profile
        return super().form_valid(form)

    def get_success_url(self):
        pk = self.object.pk
        return reverse('posts:detail', kwargs={'pk': pk})


class PostCreateCommentView(PostDetailView, FormMixin ,LoginRequiredMixin):
    """
    Comment Create View inherits from PostDetailView
    so in order to display CommentForm it was required to add FormMixin class 
    """
    form_class = CommentForm
    template_name = 'posts/comments.html'

    def get_context_data(self, **kwargs):
        """gets the form in order to be rendered, and the comments related to the post"""
        context = super().get_context_data(**kwargs)
        self.object = self.get_object()
        context['comments'] = Comment.objects.filter(post=self.object.pk)
        context['form']= self.form_class
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        """creates a form instance
         for hidden user, profile, and post fields"""
        form.instance.post= self.object
        form.instance.user= self.request.user
        form.instance.profile = self.request.user.profile
        
        if form.is_valid():
            form.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    
    def get_success_url(self):
        pk = self.object.pk
        return reverse('posts:create_comment', kwargs={'pk': pk})

    

 

templates/posts/comments.html
{% extends 'base.html' %}

{% load static %}



{% block head_content %}
<title>Comments</title>
{% endblock %}


{% block container %}
{% include 'posts/post.html'%}

<!-- form comment field -->
<div class="comment row d-flex justify-content-lg-center mb-4 sticky-top">
  <div class="col-lg-4 p-4">

    <div class="form-floating" >
      <form method="POST" action="{% url 'posts:create_comment' pk=post.pk %}">
        {% csrf_token %}
          {{ form.text }}
        <input class="btn-outline-primary offset-10" type="submit" value="Submit">
      </form>
    </div> 
  </div>
</div>
<!-- /form comment field -->

<!-- comments -->
{% for comment in comments %}
  <div class="row justify-content-lg-center">
    <div class="col-lg-5">
      <div class="row mb-2 mb-lg-3">

        <!-- user profile picture thumbnail -->
        <div class=" media col-lg-1 offset-lg-1">
          {% if comment.profile.picture %}
            <a href="{% url 'users:detail' username=post.profile.user.username %}">
              <img height="35" class="mr-3 rounded-circle" src="{{ comment.profile.picture.url }}"
                alt="{{ post.user.get_full_name }}"
              >
            </a>

          {% else %}
            <a href="{% url 'users:detail' username=post.profile.user.username %}">
              <img height="35" class="mr-3 rounded-circle" src="{% static 'img/default-profile.png' %}"
                alt="{{ post.user.get_full_name }}" id="profilepic"
              >
            </a>
          {% endif%}
        </div> 
        <!-- /user profile picture thumbnail -->


        <!-- username -->
        <div class="col-lg-3 pt-lg-2  text">
          <strong>{{comment.user.username}}</strong>: 
        </div>
        

        <!-- comment -->
        <div class="col text ms-lg-1 mb-3 pt-lg-2">
          {{comment.text}} 
        </div>
        

      </div>        
    </div>      
  </div>    
  <!-- comments -->      
{% endfor %}
  
   
  

  {% endblock %}

templates/posts/detail.html
{% extends 'base.html' %}
{% load static%}
{% load humanize %}
{% block head_content %}
    <title>Post Detail</title>
{% endblock %}

{% block container%}
<div class="col-lg-4 offset-lg-4 ">
        <!--profile user picture-->
    {# style tag need to be fixed, and place to its proper file #}
    <div
        class="media"
        {% if request.path != '/' %}
            style="margin-top: 5em;"
        {% endif %}
    >

        {% if post.profile.picture %}
            <a href="{% url 'users:detail' username=post.profile.user.username %}">
            <img
                 height="35" class="mr-3 rounded-circle"
                 src="{{ post.profile.picture.url }}"
                 alt="{{ post.user.get_full_name }}"
            >
            </a>
        {% else %}
            <a href="{% url 'users:detail' username=post.profile.user.username %}">
            <img
                 height="35" class="mr-3 rounded-circle"
                 src="{% static 'img/default-profile.png' %}"
                 alt="{{ post.user.get_full_name }}"
            >
            </a>
        {% endif%}

        <div class="media-body">
            <h5 class="mt-0">{{ post.user.username }}</h5>
        </div>
    </div>

<!--   Post picture-->
    
    {% if request.path == '/' %}
    <a 
        href="{% url 'posts:detail' pk=post.pk %}">
    {% endif %}
        <img
             class="img-fluid mt-3 border rounded"
             src="{{ post.photo.url }}" alt="{{ post.title }}"
        >
    </a>
  
    <!-- Like and comment icon -->
    <div class="row">
        {% if request.user in post.likes.all %}
            <!-- like button -->
            <div class="col-1">
                <a 
                    data-href="{% url 'posts:likeordislikepost' post=post.pk instruction='rmv'%}"
                    onclick="filledLike('{% url 'posts:likeordislikepost' post=post.pk instruction='rmv'%}')" type="button"
                    class="filledlike" >
                    
                    <i class="fas fa-heart" id="liked"></i>
                </a>
            </div>
        {% else %}
            <!-- unlike button -->
            <div class="col-1">
                <a 
                    data-href="{% url 'posts:likeordislikepost' post=post.pk instruction='like'%}" onclick="emptyLike('{% url 'posts:likeordislikepost' post=post.pk instruction='like'%}')" type="button"
                    class="emptylike" >

                    <i class="far fa-heart"></i>
                </a>
            </div>
        {% endif %}

        <p class="fw-lighter fst-italic small mt-2"> 
            {{ post.created|naturaltime }} 
        </p>
    </div>

    {% if user == post.profile.user and request.path != '/' %}

        <a
            href="{% url 'posts:update' pk=post.pk %}"
            class="ml-5 btn btn-sm btn-outline-dark"
        >
            Edit Title
        </a>

        <a
            href="{% url 'posts:delete' pk=post.pk %}" type="button"
            class="ml-5 btn btn-sm btn-outline-danger"
            class="btn btn-primary" data-bs-toggle="modal" 
            data-bs-target="#exampleModal"
        >
            Delete Post
        </a>
        <!-- Button trigger modal -->

        <!-- Modal -->
            {% include 'posts/post_confirm_delete.html' %}
            {% endif %}
            
</div>

{% endblock %}

templates/posts/feed.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
    <title>Instagram Feed</title>
{% endblock %}

{% block container %}
  <div class="row">
    {% for post in posts %}
      {% include 'posts/post.html' %}
    {% endfor %}
  </div>
{% endblock %}

templates/posts/new.html
{% extends 'base.html' %}

{% block head_content %} 
    <title>New post</title> 
{% endblock %}


{% block container %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-lg-5 p-4" id="profile-box">

            <h4 class="text-center mt-3">Publish an image</h4>
<!--        New post form-->
            <form action="{% url 'posts:create_post' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group col-sm-8 mx-auto mt-3">

                    <label> Title :</label>
                        {{ form.title }}
                </div>

                <div class="form-group mt-3">
                    {{  form.photo }}
                </div>

            <!--Publish button-->
            <div class="d-grid gap-2 col-6 mx-auto" >
                <button class="btn btn-primary btn-block mt-3" type="submit" > Publish now </button>
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/posts/post.html
{% load static %}
{% load humanize %}

<div class="col-lg-4 offset-lg-4 ">
	<!--profile user picture-->
	<div class="media mt-4"
		{% if request.path != '/' %}
				style="margin-top: 5em;"
		{% endif %}
	>

		{% if post.profile.picture %}
		
		<a href="{% url 'users:detail' username=post.profile.user.username %}">
			<img 
				loading="lazy" height="35" class="mr-3 rounded-circle profilepic" data-src="{{ post.profile.picture.url }}"
				alt="{{ post.user.get_full_name }}"
			>
		</a>

		{% else %}
		
		<a href="{% url 'users:detail' username=post.profile.user.username %}">
			<img 
				height="35" class="mr-3 rounded-circle" src="{% static 'img/default-profile.png' %}"
				alt="{{ post.user.get_full_name }}"
			>
		</a>

		{% endif%}

		<div class="media-body">
			<h5 class="mt-0">{{ post.user.username }}</h5>
		</div>
	</div>

	<!--   Post picture-->

	<span id="postpic">
		<img class="img-fluid mt-3 border rounded post" data-src="{{ post.photo.url }}" alt="{{ post.title }}">
	</span>

	<!-- Like and comment icon -->
	<div class="row">
		{% if request.user in post.likes.all %}
			<!-- like button -->
			<div class="col-1">
				<a 
					data-href="{% url 'posts:likeordislikepost' post=post.pk instruction='rmv'%}"
					onclick="filledLike('{% url 'posts:likeordislikepost' post=post.pk instruction='rmv'%}', '{{ post.pk }}')" 
					type="button"
					class="filledlike" >
					
					<i class="fas fa-heart" id="liked"></i>
				</a>
			</div>
		{% else %}
			<!-- unlike button -->
			<div class="col-1">
				<a 
					data-href="{% url 'posts:likeordislikepost' post=post.pk instruction='like'%}" onclick="emptyLike('{% url 'posts:likeordislikepost' post=post.pk instruction='like'%}', '{{ post.pk }}')" 
					type="button"
					class="emptylike" >

					<i class="far fa-heart"></i>
				</a>
			</div>
		{% endif %}

		<div class="col-2 col-md-1 ms-3 ms-md-0">
		<a href="{% url 'posts:create_comment' pk=post.pk %}">
			<i class="far fa-comment"></i>
		</a>
		</div>
	</div>

	<div>
		<div class="row">
			<div id="{{ post.pk }}" class="col-4">	
				{% if post.likes.count > 0 %}
					<p class="fw-light">
						{{post.likes.count}} Likes
					</p>
				{% endif %}
			</div>	
			
			<div class="col-6 offset-2 ">
				{% if post.comments_count > 0 %}
					<p class="fw-light">		
						{{ post.comments_count }} Comments
					</p>
				{% endif %}
			</div>

		</div>
		
		
		{% if post.title %}
		<div class="row mt-5 mt-lg-0">
			<h6 class="ml-1 mt-1">{{ post.title }}</h6>
		</div>
		{% else %}
			<p></p>
		{% endif %}

		<p class="fw-lighter fst-italic small mt-2">
			{{ post.created|naturaltime }}
		</p>
	</div>

	{% if user == post.profile.user and request.path != '/' %}

	<a href="{% url 'posts:update' pk=post.pk %}" class="ml-5 btn btn-sm btn-outline-dark">
		Edit Title
	</a>

	<a href="{% url 'posts:delete' pk=post.pk %}" class="ml-5 btn btn-sm btn-outline-danger">
		Delete Post
	</a>
	{% endif %}


</div>

templates/posts/post_confirm_delete.html
{% load static %}
{% block 'head_content' %}
    <title>Confirm delete</title>
{% endblock %}

{%  block container %}
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Confirm Delete</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="row justify-content-lg-center align-content-center mt-5" role="document">
                <div class="col">
                  <form method="post" action="{% url 'posts:delete' pk=post.pk %} ">
                    {% csrf_token %}
                    <h2 class="text">
                      Are you sure you want to delete this post "{{ object }}"?
                    </h2>
                    <hr>
                    <div class="col d-flex justify-content-end">
                    
                    <input class="btn btn-danger m-1" type="submit" value="Confirm">
                    <a 
                      class="btn btn-primary m-1" type="button"
                      data-bs-dismiss="modal"
                    >   
                      Cancel 
                    </a>
                    </div>
                  </form>
                 </div> 
             </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/posts/update_post.html
{% extends 'base.html' %}

{% block head_content %} 
    <title>Update post</title>
{% endblock %}


{% block container %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-5 p-4" id="profile-box">

            <h4 class="text-center mt-3">Edit your post title</h4>
<!--        New post form-->
            <form action="{% url 'posts:update' pk=post.pk %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div>
                    <input type="hidden">
                </div>
                <div class="form-group col-sm-8 mx-auto mt-3">

                    <label> Title :</label>
                        {{ form.title }}
                </div>

            <!--Publish button-->
            <div class="d-grid gap-2 col-6 mx-auto" >
                <button class="btn btn-primary btn-block mt-3" type="submit" > Update Title </button>
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}