instagram/urls.py
from django.contrib import admin
from django.urls import path, include
#apps
from instagram import views as local_views


# for static django files
from django.conf import settings
from django.conf.urls.static import static


media_path= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
static_path = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = [
    # local views
    path('admin/', admin.site.urls),
    path(r'', include('django.contrib.auth.urls')),
    path('test/', local_views.test, name='test'),



    # posts views
    path('', include('posts.urls', namespace='posts')),

    #user views
    path('users/', include('users.urls', namespace='users')),


] + media_path + static_path

posts/urls.py
"""Posts urls"""
from django.urls import path
from posts import views



app_name = 'posts'
urlpatterns = [
path('', views.PostsFeedView.as_view(), name='feed'),
path('post/<int:pk>/', views.PostDetailView.as_view(), name='detail' ),
path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='update' ),
path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete' ),
path('post/create/', views.CreatePostView.as_view(), name='create_post' ),
path('post/<int:pk>/comment/create/', views.PostCreateCommentView.as_view(), name='create_comment' ),
path('post/<int:post>/<str:instruction>/', views.like_or_dislike_post, name= 'likeordislikepost'),
]

users/urls.py
"""Users Urls"""
from users import views
from django.urls import path


app_name= 'users'
urlpatterns = [
path('login/', views.LoginView.as_view(), name= 'login'),
path('logout/', views.logout_view, name= 'logout'),
path('signup/', views.SignUpView.as_view(), name= 'signup'),
path('me/profile/', views.ProfileUpdateView.as_view(), name= 'update_profile'),
path('<str:username>/', views.UserDetailView.as_view() , name= 'detail'),
path('<str:username>/following/', views.FollowingView.as_view() , name= 'following'),
path('<str:username>/followers/', views.FollowersView.as_view() , name= 'followers'),
path('<int:profile>/<str:instruction>/', views.follow_or_unfollow, name= 'followorunfollow'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

<!--Boostrap files links-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" 
        crossorigin="anonymous"
    >

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous">
    </script>
<!-- Icons file link   -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
<!--Custom CSS   -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" media="(max-width: 990px)" href="{% static 'css/900pixels.css' %}">
<!--Logo    -->
    <link rel="shortcut icon" href="{% static 'img/instagram.png' %}"/>
<!-- Icon-->
    <link rel="shortcut icon" href="{% static 'img/instagramm.png' %}"/>
</head>

<!--body-->
<body>
<!-- navar -->
    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock %}
    </div>

    {% block extrajs%}
    
    {% endblock %}
    <script src="{% static 'js/lazy.js' %}"> </script>
    <script src="{% static 'js/onclickfetch.js' %}"> </script>
</body>


</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand fixed-top" id="main-navbar">
	<div class="container">

		<!--        Logo-->
		<a href="{% url 'posts:feed' %}">
			<img class="nav-logo" src="{% static 'img/instagram.png' %}" height="45" />
		</a>

		<!--    Icons profile, add and signout-->
		<div class="navbar-expand ms-auto">
			<ul class="navbar-nav">

				<!--            Logout button-->
				<li class="nav-item nav-icon ">
					<a href="{% url 'users:logout' %}">
						<i class="fas fa-sign-out-alt"></i>
					</a>
				</li>

				<!--            New post button-->
				<li class="nav-item nav-icon">
					<a href="{% url 'posts:create_post' %}">
						<i class="fas fa-plus"></i>
					</a>
				</li>

				<!--            Profile button-->
				<li class="nav-item nav-icon dropdown">
					<a class="nav-item dropdown" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
						aria-expanded="false">
						{% if user.profile.picture %}
							<img class="d-inline-block align-top rounded-circle" src="{{ user.profile.picture.url }}" height="35" />
						{% else %}
						<img class="d-inline-block align-top rounded-circle" src="{% static 'img/default-profile.png' %}"
							height="35" />
						{% endif %}
					</a>

					<!--                Dropdow profile menu-->
					<ul class="dropdown-menu pe-5" aria-labelledby="navbarDropdown">
						<li>
							<a class="dropdown-item" href="{% url 'users:detail' username=request.user.username %}">
								Profile
							</a>
						</li>

						<li>
							<hr class="dropdown-divider">
						</li>

						<li>
							<a class="dropdown-item" href="{% url 'users:update_profile' %}">
								Config
							</a>
						</li>
					</ul>
				</li>

			</ul>
		</div>
	</div>
</nav>