instagram/urls.py
from django.contrib import admin
from django.urls import path, include
#apps
from instagram import views as local_views


# for static django files
from django.conf import settings
from django.conf.urls.static import static


media_path= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
static_path = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = [
    # local views
    path('admin/', admin.site.urls),
    path(r'', include('django.contrib.auth.urls')),
    path('test/', local_views.test, name='test'),



    # posts views
    path('', include('posts.urls', namespace='posts')),

    #user views
    path('users/', include('users.urls', namespace='users')),


] + media_path + static_path

posts/urls.py
"""Posts urls"""
from django.urls import path
from posts import views



app_name = 'posts'
urlpatterns = [
path('', views.PostsFeedView.as_view(), name='feed'),
path('post/<int:pk>/', views.PostDetailView.as_view(), name='detail' ),
path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='update' ),
path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete' ),
path('post/create/', views.CreatePostView.as_view(), name='create_post' ),
path('post/<int:pk>/comment/create/', views.PostCreateCommentView.as_view(), name='create_comment' ),
path('post/<int:post>/<str:instruction>/', views.like_or_dislike_post, name= 'likeordislikepost'),
]

users/urls.py
"""Users Urls"""
from users import views
from django.urls import path


app_name= 'users'
urlpatterns = [
path('login/', views.LoginView.as_view(), name= 'login'),
path('logout/', views.logout_view, name= 'logout'),
path('signup/', views.SignUpView.as_view(), name= 'signup'),
path('me/profile/', views.ProfileUpdateView.as_view(), name= 'update_profile'),
path('<str:username>/', views.UserDetailView.as_view() , name= 'detail'),
path('<str:username>/following/', views.FollowingView.as_view() , name= 'following'),
path('<str:username>/followers/', views.FollowersView.as_view() , name= 'followers'),
path('<int:profile>/<str:instruction>/', views.follow_or_unfollow, name= 'followorunfollow'),

]

users/models.py
"""USER Models  """
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Profile(models.Model):
    """
    Profile is an User class Proxy.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(null=True, blank=True)
    biography = models.TextField(null=True, blank=True)
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    picture = models.ImageField(upload_to='users/pictures', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    # def get_absolute_url(self):
    #     return reverse('users:detail', kwargs={'username': self.user.username})

    def __str__(self):
        return f' @{self.user.username}'



class Contact(models.Model):
    """
    Following and followers system.
    followers acces will be trough the profile model.
    eg: 'profile.followers.count' will return Contact objects
    """
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    following= models.ManyToManyField(Profile, related_name='followers', blank=True)


    @classmethod
    def follow(cls, profile, another_profile):
        object = cls.objects.get(profile=profile)
        object.following.add(another_profile)

    @classmethod
    def unfollow(cls, profile, another_profile):
        object = cls.objects.get(profile=profile)
        object.following.remove(another_profile)

    def following_count(self):
        return self.following.count()
    
    
    def __str__(self):
        return f'profile: {self.profile}, Following : {self.following.all()}'

users/forms.py
"""User Form models """
#django
from django.forms.widgets import FileInput, NumberInput, Textarea, TextInput, PasswordInput, EmailInput
from django import forms
from .models import Profile
from posts.models import Post
from django.core.exceptions import ValidationError

#models
from django.contrib.auth.models import User
from users.models import Profile, Contact

#Profile
class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['picture', 'biography', 'website', 'phone_number','user']
        exclude =['user']
        widgets = {'picture': FileInput(attrs={'class' : 'form-control'}),
            'phone_number': NumberInput(attrs={
            'class': 'form-control',
            'placeholder': '(optional)',
            'type': 'number',
            }),
            'website': TextInput(attrs={
            'class': 'form-control',
            'placeholder': '(optional)'
            }),
            'biography': Textarea(attrs={
            'cols':4,
            'rows': 4,
            'class': 'form-control',
            'placeholder': 'You must provide a small biography, or a profile picture.'
            }),
        }


    def clean(self):
        cleaned_data = super().clean()
        picture = cleaned_data.get('picture')
        biography = cleaned_data.get('biography')


        if not picture and not biography:
            raise ValidationError('You must provide a profile picture or a biography text to proceeed.')




#Signup
class SignUpForm (forms.Form):

    username = forms.CharField(max_length=50, min_length=4,label=False ,widget=TextInput(attrs={
        'class' : 'form-control mt-1',
        'placeholder': 'Username'
    }) )
    password = forms.CharField(label=False, min_length=6, widget=PasswordInput(attrs={
        'class' : 'form-control mt-1',
        'placeholder': 'Password'
    }) )
    password_confirm = forms.CharField(label=False, min_length=6, widget=PasswordInput(attrs={
        'class' : 'form-control mt-1',
        'placeholder': 'Confirm Password',

    }) )
    email = forms.CharField(label=False, max_length=100, required=False, widget=EmailInput(attrs={
        'class' : 'form-control mt-1',
        'placeholder': 'Email (optional)'
    }) )
    first_name = forms.CharField( label=False, required=False, max_length=50, min_length=4, widget=TextInput(attrs={
        'class' : 'form-control mt-1',
        'placeholder': 'First Name (optional)'
    }) )


    def clean_username(self, *args, **kwargs):
        username = self.cleaned_data['username']
        #Chek if username already exist in the database
        check_duplicate = User.objects.filter(username=username)
        if not check_duplicate:
            return username
        else:
            raise ValidationError('Username already registered')

    def clean_email(self):
        email = self.cleaned_data['email']
        # Defaul value for empty email field is '', so we need to filter default value
        if email !='' :
            # Check if email already exist in the database
            check_duplicate = User.objects.filter(email=email)
            if not check_duplicate:
                return email
            else:
                raise ValidationError('Email already registered')
        else:
            return email

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if password and password_confirm:

            if password != password_confirm :
                raise ValidationError("Passwords fields didn't match ")

    def save(self):
        data = self.cleaned_data
        data.pop('password_confirm')

        user = User.objects.create_user(**data)
        #Also creates a Profile
        profile = Profile(user=user)
        profile.save()

        # And also creates contact system
        contact = Contact(profile=profile)
        contact.save()

users/views.py
"""USERS VIEWS"""
#django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect,reverse
from django.contrib.auth import authenticate,login, logout
from django.views.generic import DetailView, ListView, FormView
from django.views.generic.edit import UpdateView
from django.contrib.auth import views as auth
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect

#models
from .models import Profile, Contact
from posts.models import Post
from users.models import User


#forms
from .forms import ProfileForm
from posts.forms import PostForm
from users.forms import SignUpForm

# Views


class FollowersView(LoginRequiredMixin, DetailView):
    """Followers View"""
    model = User
    template_name = 'users/followers.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    context_object_name = 'users'

class FollowingView(LoginRequiredMixin, DetailView):
    """Following view"""
    model = User
    template_name = 'users/following.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    context_object_name = 'users'

class FollowOrUnforllowView(UpdateView, LoginRequiredMixin):
    """ does't work yet
    trying to transform de follow_or_unfollow in a class view"""
    slug_field = 'username'
    slug_url_kwarg = 'username'

@login_required
def follow_or_unfollow(request, profile, instruction):
    """Follow or unfollow view"""
    current_profile = request.user.profile
    another_profile = get_object_or_404(Profile, pk=profile)

    if instruction == "add":
        """
        follows another_profile is instruccion == 'add' 
        otherwhise unfollows
        """
        Contact.follow(current_profile,another_profile)
    else:
        Contact.unfollow(current_profile,another_profile)


    return HttpResponseRedirect(request.META['HTTP_REFERER'])


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    """Profile update view"""
    model = Profile
    form_class = ProfileForm
    template_name = 'users/update_profile.html'

    def get_object(self, queryset=None):
        """ Return user's profile """
        return self.request.user.profile

    def get_success_url(self):
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username': username})


class UserDetailView(DetailView, LoginRequiredMixin):
    """Class view for user detail"""
    slug_field = 'username'
    slug_url_kwarg = 'username'
    template_name='users/detail.html'
    model = User
    context_object_name = 'users'


    def get_context_data(self, **kwargs):
        """Gets the user profile and its posts"""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context


class LoginView(auth.LoginView):
    """ Login View"""
    template_name = 'users/login.html'
    redirect_field_name = 'posts:feed'
    redirect_authenticated_user = True


@login_required
def logout_view (request):
    logout(request)
    return render(request, 'users/login.html', {'error': 'You logged out succesfully'})


class SignUpView(FormView):
    """Signup View"""
    template_name = 'users/signup.html'
    success_url = 'posts:feed'
    form_class = SignUpForm

    def form_valid(self, form):
        # save the new user
        form.save()
        # get the username and password
        username = self.request.POST['username']
        password = self.request.POST['password']
        # authenticate user then login
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return redirect(self.get_success_url())

templates/users/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	{% block head_content %}
	{% endblock %}

	{% load static %}
	<!--    boostrap -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
	<!-- custom css -->
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" media="(max-width: 990px)" href="{% static 'css/900pixels.css' %}">
	<!-- fontawsome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
	<!-- icon -->
	<link rel="shortcut icon" href="{% static 'img/instagramm.png' %}" />
</head>

<body>
	<div class="container-lg h-100 ">
		<div class="row h-100 justify-content-center align-items-center">
			<div class="col-md-5 pt-2 pb-5" id="auth-container">
				<img class="img-fluid rounded mx-auto d-block pb-5 pt-4" src="{% static 'img/instagram.png' %}"
					style="max-width: 60%;">

				{% block container %}{% endblock%}
			</div>
		</div>
	</div>

</body>

</html>

templates/users/detail.html
{% extends 'base.html' %}
{% load static %}
{% block head_content %}
<title> @{{ users.username }}</title>
{% endblock %}

{% block container %}

{# style tag need to be fixed and placed to it's proper file #}
<div class="container mb-5" style="margin-top: 8em;">
	<div class="row">
		<!--profile picture username    -->
		<div class="col-sm-4 d-flex justify-content-center	">
			{% if users.profile.picture %}
			<img src="{{ users.profile.picture.url }}" alt="@{{ user.username}}" class="rounded-circle" width="150px" />
			{% else %}
			<img src="{% static 'img/default-profile.png' %}" alt="@{{ user.username}}" class="rounded-circle"
				width="150px" />
			{% endif %}
		</div>

		<!--            Big profile name, edit or follow botton-->
		<div class="col-sm-8 ">
			<h2>
				{{ users.username }}
				{% if users == request.user %}
				<a href="{% url 'users:update_profile' %}" class="ml-5 btn btn-sm btn-outline-dark">
					Edit profile
				</a>
				{% else %}
				{% if users.profile not in user.profile.contact.following.all %}
				<a href="{% url 'users:followorunfollow' profile=users.profile.pk instruction='add'%}"
					class="ml-5 btn btn-sm btn-primary">
					Follow
				</a>
				{% else %}
				<a href="{% url 'users:followorunfollow' profile=users.profile.pk instruction='rm'%}"
					class="ml-5 btn btn-sm btn-danger">
					Unfollow
				</a>
				{% endif %}
				{% endif %}
			</h2>
			<div class="row mt-2" style="font-size: 1.2em"> {#style tag to relocatte#}
				<!--    posts count-->

				<div class="col-sm-4">
					<b>{{ posts.count }}</b> Posts
				</div>

				<!--   	following count-->
				<div class="col-sm-4">

					{% if users.profile.contact.following.count %}
					<a href="{% url 'users:following' username=users.username%}">
						<b>{{ users.profile.contact.following.count }}</b>
					</a>
					Following

					{% else %}
					<b> 0 </b> Following
					{% endif %}
				</div>
				<!--                followers count -->
				<div class="col-sm-4">
					{% if users.profile.followers.count %}
					<a href="{% url 'users:followers' username=users.username %}">
						<b>{{ users.profile.followers.count }}</b>
					</a>
					Followers

					{% else %}
					<b> 0 </b> Followers
					{% endif %}
				</div>
			</div>
			<div class="row mt-4">
				<div class="col-">
					<p>{{ users.profile.biography }}</p>
				</div>
			</div>
		</div>
	</div>
</div>
<hr>


<div class="container" id="user-posts">
	<div class="row mt-3">
		<!--        List username posts-->
		{% for post in posts %}
		<div class="col-sm-4 pt-5 pb-5 d-flex justify-content-center align-items-center">
			<a href="{% url 'posts:create_comment' pk=post.pk %}" class="border">
				<img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid" />
			</a>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}

templates/users/followers.html
{% extends 'base.html' %}
{% load static%}
{% block head_content %}
<title>Followers</title>
{% endblock %}

{% block container%}

<div class="container">
	<div class="row d-flex justify-content-md-center align-content-center">
		<div class=" col-12 col-md-3 p-2" id="profile-box">
				<h2 class="text text-md-center">Followers:</h2>
			<table class="table table-striped table-hover">
				<tr>
					<td>
						{% for contact in users.profile.followers.all %}
						<div class="media ms-md-3">
							{% if contact.profile.picture %}
							<a href="{% url 'users:detail' username=contact.profile.user.username %}">
								<img height="35" class="mr-3 rounded-circle" src="{{ contact.profile.picture.url }}"
									alt="{{ contact.profile.user.get_full_name }}">
							</a>
							{% else %}
							<a href="{% url 'users:detail' username=contact.profile.user.username %}">
								<img height="35" class="mr-3 rounded-circle" src="{% static 'img/default-profile.png' %}"
									alt="{{ contact.profile.user.get_full_name }}">
							</a>
							{% endif %}
							<div class="media-body">
								<h6 class="mt-0">{{ contact.profile.user.username }}</h6>
							</div>
						</div>
					</td>
				</tr>
			</table>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}




		

templates/users/following.html
{% extends 'base.html' %} {% load static%} 

{% block head_content %}
<title>Following</title>
{% endblock %} 

{% block container%}

<div class="container">
  <div class="row d-flex justify-content-md-center align-content-center">
    <div class=" col-12 col-md-3 p-2" id="profile-box">
      <h2 class="text text-md-center">Following:</h2>
      <table class="table table-striped table-hover">
				<tr>
					<td>
            {% for profile in users.profile.contact.following.all %}
              <div class="media">
                {% if profile.picture %}
                  <a href="{% url 'users:detail' username=profile.user.username %}">
                    <img
                      height="35"
                      class="mr-3 rounded-circle"
                      src="{{ profile.picture.url }}"
                      alt="{{ profile.user.get_full_name }}"
                    />
                </a>
                {% else %}
                  <a href="{% url 'users:detail' username=profile.user.username %}">
                    <img
                      height="35"
                      class="mr-3 rounded-circle"
                      src="{% static 'img/default-profile.png' %}"
                      alt="{{ contact.profile.user.get_full_name }}"
                    />
                  </a>
                {% endif %}
                <div class="media-body">
                  <h6 class="mt-0">{{ profile.user.username }}</h6>
                </div>
              </div>
            {% endfor %}
          </td>
        </tr>    
      </table>      
    </div>
  </div>
</div>
{% endblock %}

templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}

{% block head_content %}
<title> Instagram Sign in </title>
{% endblock %}

{% block container %}

{% if form.errors %}
    <div class="alert alert-danger col-sm-10 mx-auto" role="alert" >
        <p>{{form.errors}}</p>
    </div>  
{% endif %}

<div class="col-sm-12 pt-4">
    <form  method="POST" action="{% url 'users:login' %}" >
        {% csrf_token %}

    <!--Username and password input-->
        <div class="form-group col-sm-8 mx-auto">
            <input class="form-control"  type="text" placeholder="Username" name="username" >
        </div>

        <div class="form-group col-sm-8 mx-auto mt-1">
            <input class="form-control"  type="password" placeholder="Password" name="password">
        </div>

    <!--Login button-->
        <div class="d-grid gap-2 col-6 mx-auto" >
            <button class="btn btn-primary btn-block mt-3" type="submit" > Login</button>
        </div>
    </form>
    <!--New account registration-->
    <div class="fw-lighter text-center mt-5">
        <p> Don't have an account? </p> <a class="fw-lighter text-center" href="{% url 'users:signup' %}">Register</a>
    </div>

</div>

{% endblock %}

templates/users/signup.html
{% extends 'users/base.html' %}
{% load static %}

<!--head-->
{% block head_content %}
<title> Signup </title>
{% endblock %}

<!--body-->
{% block container %}
<div class="text-center">
   <p> Register the fields below </p>
</div>

<!--Alerts-->
{% if form.non_field_errors %}
    <div class="alert alert-danger col-sm-10 mx-auto" role="alert" >
       <p> {{ form.non_field_errors }}</p>
    </div>
{% endif %}


<form  method="POST" action="{% url 'users:signup' %}" >
    {% csrf_token %}

<!--Signup form-->
    <div class="form-group col-sm-8 mx-auto mt-1">
        {% for field in form %}
            {% if field.errors %}
                <div class="alert alert-danger" role="alert" >
                    {{ field.errors }}
                </div>
            {% endif %}
            <div class="fieldWrapper">
                {{ field }}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        {%endfor%}
    </div>


<!--  Signup Bottom-->
    <div class="d-grid gap-2 col-6 mx-auto" >
        <button class="btn btn-primary btn-block mt-3" type="submit" > Sign up</button>
    </div>

</form>

<!--Back to login link-->

<div class="fw-lighter text-center mt-5">
    <p> Do you have an account already? </p>
    <a href="{% url 'users:login' %}">Login</a>
</div>

{% endblock%}

templates/users/update_profile.html
{% extends 'base.html' %}
{% load static %}
{% block 'head_content %}
    <title>Update Profile</title>
{% endblock %}

{%  block container %}

{# Style tag need to be fixed and placed to it's proper file#}
<div class="form-group col-sm-4 mx-auto" style="margin-top: 6em;">

{% if form.errors %}
    <div class="alert alert-danger col-sm-10 mx-auto" role="alert" >
        {{ form.error }} {{ form.non_field_errors }}
    </div>
{% endif %}

    <div class="media">
        {% if  user.profile.picture %}
            <img src="{{ user.profile.picture.url }}" class="rounded-circle" height="50" />
        {% else%}
            <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
        {% endif %}

        <div>
            <div class="media-body">
                <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                <p class="ml-4">
            </div>

            <form  method="POST" action="{% url 'users:update_profile' %}" enctype="multipart/form-data" >
                {% csrf_token %}
                {{ form }}

                <div class="d-grid gap-2 col-6 mx-auto" >
                    <button class="btn btn-primary btn-block mt-3" type="submit" > Send</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}